name: MEC-11

on: 
  push:
    paths:
    - 'mec11/**'

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build debug 
      run: cargo build --verbose
      working-directory: mec11

    - name: Run tests
      run: cargo test --verbose
      working-directory: mec11

    - name: Build release 
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: mec11-x86-release
        path: target/release/mec11
