name: Rust

on: push
  paths:
  - 'mec11/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: mec11
    - name: Run tests
      run: cargo test --verbose
      working-directory: mec11

